using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Template.Editor.CodeGeneration;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace Template.Editor.CodeGeneration
{
    public static class AddressableKeyGenerator
    {
        private const string OutputPath = "Assets/Scripts/Generated/AddressableKeys.cs";

        [MenuItem("Tools/Template/Code Generation/Generate Addressable Keys")]
        public static void Generate()
        {
            var content = BuildExpectedContentOrThrow();
            var changed = GeneratedCodeUtility.WriteIfChanged(OutputPath, content);
            if (changed)
            {
                AssetDatabase.Refresh();
            }

            Debug.Log(changed
                ? $"[CodeGeneration] Generated {OutputPath}."
                : $"[CodeGeneration] Addressable keys already current: {OutputPath}.");
        }

        [MenuItem("Tools/Template/Code Generation/Validate Addressable Keys")]
        public static void ValidateOrThrow()
        {
            var expected = BuildExpectedContentOrThrow();
            if (!GeneratedCodeUtility.ContentMatches(OutputPath, expected))
            {
                throw new InvalidOperationException(
                    $"Generated Addressable keys are stale. Run Generate Addressable Keys: {OutputPath}");
            }

            Debug.Log("[CodeGeneration] Addressable keys validation passed.");
        }

        internal static string BuildExpectedContentOrThrow()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                throw new InvalidOperationException("Addressable Asset Settings not found.");
            }

            var labels = settings.GetLabels();
            var addresses = CollectAddresses(settings);
            var labelsValid = GeneratedCodeUtility.TryCreateConstants(
                labels,
                "Addressable labels",
                out var labelConstants,
                out var labelError);
            var assetsValid = GeneratedCodeUtility.TryCreateConstants(
                addresses,
                "Addressable asset addresses",
                out var assetConstants,
                out var assetError);
            if (!labelsValid || !assetsValid)
            {
                throw new InvalidOperationException(
                    string.Join(Environment.NewLine, new[] { labelError, assetError }
                        .Where(message => !string.IsNullOrEmpty(message))));
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Generated from Addressable Asset Settings. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("namespace Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class AddressableKeys");
            builder.AppendLine("    {");
            WriteConstantsClass(builder, "Labels", labelConstants);
            builder.AppendLine();
            WriteConstantsClass(builder, "Assets", assetConstants);
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static IEnumerable<string> CollectAddresses(AddressableAssetSettings settings)
        {
            foreach (var group in settings.groups)
            {
                if (group == null || group.ReadOnly)
                {
                    continue;
                }

                foreach (var entry in group.entries)
                {
                    yield return entry.address;
                }
            }
        }

        private static void WriteConstantsClass(
            StringBuilder builder,
            string className,
            IReadOnlyList<GeneratedConstant> constants)
        {
            builder.AppendLine($"        public static class {className}");
            builder.AppendLine("        {");
            foreach (var constant in constants)
            {
                builder.AppendLine(
                    $"            public const string {constant.Identifier} = \"" +
                    $"{GeneratedCodeUtility.EscapeStringLiteral(constant.Value)}\";");
            }

            builder.AppendLine("        }");
        }
    }
}
