using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace Editor
{
    public static class AddressableKeyGenerator
    {
        // 生成文件的路径
        private const string OutputPath = "Assets/Scripts/Generated/AddressableKeys.cs";
        // 生成的类名
        private const string ClassName = "AddressableKeys";

        [MenuItem("Tools/Aoyeningluosi/Generate Addressable Keys")]
        public static void Generate()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogError("Addressable Asset Settings not found!");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// This file is automatically generated. Do not modify it manually.");
            sb.AppendLine("public static class " + ClassName);
            sb.AppendLine("{");

            // 1. 生成 Labels
            sb.AppendLine("    public static class Labels");
            sb.AppendLine("    {");
            var labels = settings.GetLabels();
            foreach (var label in labels)
            {
                string varName = SanitizeName(label);
                sb.AppendLine($"        public const string {varName} = \"{label}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // 2. 生成 Keys (Assets)
            sb.AppendLine("    public static class Assets");
            sb.AppendLine("    {");
        
            var processedKeys = new HashSet<string>();

            foreach (var group in settings.groups)
            {
                if (group == null || group.ReadOnly) continue; // 跳过只读组（如 Built-in）

                foreach (var entry in group.entries)
                {
                    // 获取地址（Address），这是我们在代码中加载用的 Key
                    string address = entry.address;
                
                    // 简单的去重处理
                    if (processedKeys.Contains(address)) continue;
                    processedKeys.Add(address);

                    string varName = SanitizeName(address);
                    // 如果变量名以数字开头，加个下划线
                    if (char.IsDigit(varName[0])) varName = "_" + varName;

                    sb.AppendLine($"        public const string {varName} = \"{address}\";");
                }
            }
            sb.AppendLine("    }");

            sb.AppendLine("}");

            // 确保目录存在
            var dir = Path.GetDirectoryName(OutputPath);
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            // 写入文件
            File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
        
            Debug.Log($"Addressable Keys generated at: {OutputPath}");
        }

        // 将字符串转换为合法的 C# 变量名
        private static string SanitizeName(string name)
        {
            // 替换非法字符为下划线
            string pattern = "[^a-zA-Z0-9_]";
            string result = Regex.Replace(name, pattern, "_");
            return result;
        }
    }
}